"""Add bill model

Revision ID: 1ba09ffedfb6
Revises: c82053ca87b4
Create Date: 2025-09-30 00:17:05.139366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ba09ffedfb6'
down_revision = 'c82053ca87b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bill', 'name',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
    op.alter_column('bill', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
    op.alter_column('bill', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)
    op.alter_column('bill', 'is_paid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bill', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('goal', 'target_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('goal', 'current_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goal', 'current_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('goal', 'target_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('bill', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bill', 'is_paid',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bill', 'due_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bill', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('bill', 'name',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
    # ### end Alembic commands ###
